#! /usr/bin/env bash

# Determine the correct script location and set minimal variables
pushd $(dirname ${BASH_SOURCE[0]}) > /dev/null
    DIX_PATH=$(pwd -P)
popd > /dev/null

# Source the library
source $DIX_PATH/opt/dix/lib/dix.sh || exit 1

# save to environment to disk and then load it
dix.env.save $DIX_PATH $DIX_PATH/var/env
dix.env.load $DIX_PATH/env

# This file is just a wrapper for the pkg library
[[ ! $1 ]] && dix.error "Expecting a verb"
! type.is_func pkg.$1 && dix.error "Invalid verb"
pkg.$@