#! /usr/bin/env bash

# Determine the real path of the symlink and go up a dir until dix is found.
PWD=`dirname $(perl -le "use Cwd qw(realpath); print realpath('${BASH_SOURCE[0]}')")`
pushd $PWD > /dev/null
	while true; do
		DIX_PATH=`pwd -P`
		[ -d ".git" ] && break
		cd ..
	done
popd > /dev/null

# Populate the environment
paths=$(find $DIX_PATH/srv -maxdepth 1 -type f ! -name "README.md")
for path in ${paths[@]}; do declare -x "`basename $path`"="`cat $path`"; done

# Allow scripts to validate if this was already loaded
DIX=true

# load utilities
paths=$(find $DIX_PATH_SELF -maxdepth 1 -type f -name "*.sh")
for path in ${paths[@]}; do source "$path"; done

# clear unneeded variables
unset paths
