#! /usr/bin/env bash

# Install the main dix script
pushd $(dirname ${BASH_SOURCE[0]}) > /dev/null

    # The variable that rules them all.
    DIX_PATH=$(pwd -P)

    # Set and store  environment variables
    DIRS=`find $DIX_PATH -maxdepth 1 -type d ! -name ".*" ! -path $DIX_PATH`
    for DIR in ${DIRS[@]}; do
        # Get the name of the dir and convert it to uppercase.
        NAME=DIX_PATH_`basename $DIR | tr '[:lower:]' '[:upper:]'`
        # If non-existant, create a file for the environment variable
        echo "$DIR" > "$DIX_PATH/srv/$NAME"
    done

    # Store the variables so the main script restores them
    echo "$DIX_PATH" > $DIX_PATH/srv/DIX_PATH
    echo "$DIX_PATH/lib/dix/dix.sh" > $DIX_PATH/srv/DIX_PATH_SELF

    # This is it, Install dix to $HOME
    rm -f $HOME/.dix
    ln -sf $DIX_PATH/sbin/dix $HOME/.dix

popd > /dev/null

# Source the library and show menu
source $HOME/.dix || exit 1
dix.menu && clear
