#! /usr/bin/env bash

# Determine the correct script location and set minimal variables
pushd $(dirname ${BASH_SOURCE[0]}) > /dev/null
    DIX_PATH=$(pwd -P)
popd > /dev/null

# Source the library
source $DIX_PATH/lib/dix.sh || exit 1

# set the environment and then load dix.
dix.env_set $DIX_PATH $DIX_PATH/srv
dix.load

# This file is just a wrapper for the pkg library
[[ ! $1 ]] && dix.error "Expecting a verb"
! type.is_func pkg.$1 && dix.error "Invalid verb"
pkg.$@