#! /usr/bin/env bash
[[ "${BASH_SOURCE[0]}" != "${0}" ]] && >&2 echo "Sourcing disabled" && exit 1
[[ ! $DIX ]] && source $HOME/.dix

relpath=$(path.relative $DIX_PATH_ETC $HOME)
dix=$(find $DIX_PATH_ETC -maxdepth 1 ! -path $DIX_PATH_ETC ! -name 'README.md')

for dotfile in ${dix[@]}; do
    back=''
    name=$(basename $dotfile)
    path=$HOME/.$name

    # Detect if there's a file already there
    if [[ -e $path ]]; then

        # Is this one of our symlinks?
        [[ "$(dirname $(path.real $path))" == "$DIX_PATH_ETC" ]] && continue

        # not ours, back it up
        mv $path $HOME/$name.bak
        back=true
    fi

    # Relative-Symlink the bastard
    pushd "$HOME" > /dev/null
        ln -s $relpath/$name  ".$name"
    popd > /dev/null
    log.info "Symlinked $([ $back ] && printf '(existing) ') $name"

done