#! /usr/env/bash

[[ ! -L $HOME/.dotfiles ]] && >&2 echo "Install Dotfiles before running" && return 1

# Determine the real path of the symlink and go up a dir until dotfiles is found.
pushd `dirname $(perl -le "print readlink '${BASH_SOURCE[0]}'")` > /dev/null
	while true; do
		DOTFILES_PATH=`pwd -P`
		[ -d ".git" ] && break
		cd ..
	done
popd > /dev/null

# Populate the environment
paths=$(find $DOTFILES_PATH/srv -maxdepth 1 -type f ! -name "README.md")
for path in ${paths[@]}; do declare -x "`basename $path`"="`cat $path`"; done

# Allow scripts to validate if this was already loaded
DOTFILES=true

# load utilities
paths=$(find $DOTFILES_PATH_SELF -maxdepth 1 -type f -name "*.sh")
for path in ${paths[@]}; do source "$path"; done

# clear unneeded variables
unset paths
