#! /usr/env/bash

# Returns the real path of a symbolic link.
ls.readlink() {
    [ ! -z "$1" ] && echo $(src=$1 perl -le 'print readlink $ENV{src}')
}
# TODO: Validate that dotfiles are actually a sym
# Determine the real path of the symlink and go up a dir until dotfiles is found.
pushd `dirname $(ls.readlink ${BASH_SOURCE[0]})` > /dev/null
	while true; do
		DOTFILES_PATH=`pwd -P`
		[ -d ".git" ] && break
		cd ..
	done
popd > /dev/null

# Returns all valid files on dotfiles/srv
ls.path_srv() {
    find $DOTFILES_PATH/srv -maxdepth 1 -type f ! -name "README.md"
}

# Populate the environment
for path in `ls.path_srv`; do declare -x "`basename $path`"="`cat $path`"; done

# Returns all valid files on the same directory as this file
ls.path_self(){
    find $DOTFILES_PATH_SELF -maxdepth 1 -type f -name "*.sh"
}
# Allow scripts to validate if this was already loaded
DOTFILES=true

# load utilities
for path in `ls.path_self`; do source "$path"; done

# clear unneeded variables
unset path
