#! /usr/bin/env bash
[[ "${BASH_SOURCE[0]}" != "${0}" ]] && >&2 echo "Sourcing disabled" && exit 1
[[ ! $DOTFILES ]] && source $HOME/.dotfiles

dotfiles=`find $DOTFILES_PATH_ETC -maxdepth 1 ! -path $DOTFILES_PATH_ETC ! -name 'README.md'`
for dotfile in ${dotfiles[@]}; do
	name=$(basename $dotfile)
	path=$HOME/.$name
	real=$(dirname `path.real $path`)
	[[ ! -L "$path" || "$real" != "$DOTFILES_PATH_ETC"  ]] && continue
	rm -Rf $path && log.info "Removed $name"
done
